#ifndef ANTCOLONYOPTIMIZATION_GLOBAL_H
#define ANTCOLONYOPTIMIZATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ANTCOLONYOPTIMIZATION_LIBRARY)
#  define ANTCOLONYOPTIMIZATION_EXPORT Q_DECL_EXPORT
#else
#  define ANTCOLONYOPTIMIZATION_EXPORT Q_DECL_IMPORT
#endif

#endif // ANTCOLONYOPTIMIZATION_GLOBAL_H
